services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: always
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - caddy_network
    env_file: 
      - .env

volumes:
  qdrant_data:
    driver: local

networks:
  caddy_network:
    external: true