services:
  qdrant:
    image: qdrant/qdrant:v1.14.0
    container_name: qdrant
    restart: always
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - caddy_network
    env_file: 
      - .env
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1"

volumes:
  qdrant_data:
    driver: local

networks:
  caddy_network:
    external: true